version: "3.8"

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: recipe-scheduler-api
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - PORT=$NODE_LOCAL_PORT
    volumes:
      - db-data:/app/data
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  # Worker Service
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: recipe-scheduler-worker
    env_file: ./.env
    volumes:
      - db-data:/app/data
    depends_on:
      - redis
      - api
    networks:
      - app-network
    restart: unless-stopped

  # Redis Service (for BullMQ)
  redis:
    image: redis:alpine
    container_name: cooking-scheduler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
